<?php
session_start();
require("sessions.php");
if(strlen($_SESSION['themecolour'])=="6"){
echo "<style>";
echo "#topbar table{border-bottom:1px solid #".$_SESSION['themecolour'].";}";
echo "#topbar #logo{background-color:#".$_SESSION['themecolour'].";}";
echo "#topbar #menu .link{color:#".$_SESSION['themecolour'].";}";
echo "#usermenu .item a{color:#".$_SESSION['themecolour'].";}";
echo "#topbar #search #terms{color:#".$_SESSION['themecolour']."; border:1px solid #".$_SESSION['themecolour']."; border-top:none; border-bottom:none;}";
echo "#topbar #search #go{border:1px solid #".$_SESSION['themecolour']."; color:#".$_SESSION['themecolour'].";}";
echo "#topbar #user #button{background-color:#".$_SESSION['themecolour'].";}";
echo "#topbar #user #button:hover{border:3px solid #".$_SESSION['themecolour'].";}";
echo "#topbar #user #notifcount{color:#".$_SESSION['themecolour'].";}";
echo "#posts #getsort{background-color:#".$_SESSION['themecolour'].";}";
echo "#posts #sorter .sortopt{color:#".$_SESSION['themecolour']."; border:1px solid #".$_SESSION['themecolour'].";}";
echo "#posts #sorter .sortopt:hover{background-color:#".$_SESSION['themecolour'].";}";
echo "#newshare .postcapt{border:1px solid #".$_SESSION['themecolour'].";}";
echo "#newshare .postshare{background-color:#".$_SESSION['themecolour'].";}";
echo "#posts #newshare .postcapt{border:1px solid #".$_SESSION['themecolour'].";}";
echo "#posts #newshare .postshare{background-color:#".$_SESSION['themecolour'].";}";
echo "#wide #sidebar{border-right:1px solid #".$_SESSION['themecolour'].";}";
echo "#wide #sidebar #sideprof #user:hover{border-bottom:2px solid #".$_SESSION['themecolour'].";}";
echo "#wide #notifs{border-left:1px solid #".$_SESSION['themecolour'].";}";
echo "#wide #sidebar #sidemenu .item:hover{background-color:#".$_SESSION['themecolour'].";}";
echo "#wide #sidebar #sidestory #subtitle{border-top:1px solid #".$_SESSION['themecolour'].";}";
echo "#wide #notifs .nitem:hover{border-bottom:1px solid #".$_SESSION['themecolour'].";}";
echo "#wide #sidebar #sideprof #user #name{color:#".$_SESSION['themecolour'].";}";
echo "#wide #sidebar #sideprof #user #proflink{color:#".$_SESSION['themecolour'].";}";
echo "#usermenu{border:1px solid #".$_SESSION['themecolour']."; border-top:none; border-right:none;}";
echo "#usermenu .item:hover{background-color:#".$_SESSION['themecolour'].";}";
echo "#usermenu .mobileitem:hover{background-color:#".$_SESSION['themecolour'].";}";
echo "#main #bigmessage{background-color:#".$_SESSION['themecolour']."; color:#ffffff;}";
echo "#main #bigmessage #smallmessage{background-color:#".$_SESSION['themecolour']."; color:#ffffff;}";
echo "#main #sidebar{border-right:5px solid #".$_SESSION['themecolour'].";}";
echo "#main #sidebar .itemlink{background-color:#ffffff; color:#".$_SESSION['themecolour'].";}";
echo "#main #sidebar .itemlink:hover{background-color:#".$_SESSION['themecolour']."; color:#ffffff;}";
echo "#main #helpmain .entry{border-bottom:3px solid #".$_SESSION['themecolour'].";}";
echo "#main #helpmain .entry .title{color:#".$_SESSION['themecolour'].";}";
echo "#main #support{background-color:#".$_SESSION['themecolour'].";}";
echo "#main #support #supportbutton{background-color:#".$_SESSION['themecolour']."; color:#ffffff;}";
echo "#main #support #supportbutton:hover{background-color:#ffffff; color:#".$_SESSION['themecolour'].";}";
echo "#searchbox #sidebar .sorters{color:#".$_SESSION['themecolour'].";}";
echo "#searchbox #sidebar .sorters:hover{background-color:#".$_SESSION['themecolour'].";}";
echo "#searchbox #mobilesearch #terms{color:#".$_SESSION['themecolour'].";}";
echo "#searchbox #mobilesearch #go{color:#".$_SESSION['themecolour'].";}";
echo "#searchbox .userentry .name{color:#".$_SESSION['themecolour'].";}";
echo "#searchbox .storyentry .name{width:auto; padding:5px; color:#".$_SESSION['themecolour'].";}";
echo "#searchbox .storyentry .blurb{color:#".$_SESSION['themecolour'].";}";
echo "#notifs .option{color:#".$_SESSION['themecolour'].";}";
echo "#notifs .yeseenitem:hover, #notifs .ntseenitem:hover{border-bottom:1px solid #".$_SESSION['themecolour'].";}";
echo "#notifs .del{color:#".$_SESSION['themecolour'].";}";
echo "#main #sidesection .tablink{color:#".$_SESSION['themecolour'].";}";
echo "#main #sidesection .tablink:hover{background-color:#".$_SESSION['themecolour'].";}";
echo "#main #sidesection #backget{background-color:#".$_SESSION['themecolour'].";}";
echo "#main #mainsection .title #sideget:hover{color:#".$_SESSION['themecolour'].";}";
echo "#main #mainsection .fieldin:focus{border:1px solid #".$_SESSION['themecolour'].";}";
echo "#main #mainsection .colourin:focus{border:1px solid #".$_SESSION['themecolour'].";}";
echo "#main #mainsection .filelabel{background-color:#".$_SESSION['themecolour'].";}";
echo "#main #mainsection .filelabel:hover{color:#".$_SESSION['themecolour'].";}";
echo "#main #mainsection .filedel{background-color:#".$_SESSION['themecolour'].";}";
echo "#main #mainsection .filedel:hover{color:#".$_SESSION['themecolour'].";}";
echo "#main #mainsection .selectin:focus{border:1px solid #".$_SESSION['themecolour'].";}";
echo "#main #mainsection .fieldlink{color:#".$_SESSION['themecolour'].";}";
echo "#main #mainsection .fieldlink:hover{background-color:#".$_SESSION['themecolour']."; border:1px solid #".$_SESSION['themecolour'].";}";
echo "#main #mainsection .smallfieldin:focus{border:1px solid #".$_SESSION['themecolour'].";}";
echo "#main #mainsection .longfieldin:focus{border:1px solid #".$_SESSION['themecolour'].";}";
echo "#main #mainsection .bigtext:focus{border:1px solid #".$_SESSION['themecolour'].";}";
echo ".buttonbox .savebutton{color:#".$_SESSION['themecolour']."; border:1px solid #".$_SESSION['themecolour'].";}";
echo ".buttonbox .savebutton:hover{color:#".$_SESSION['themecolour'].";}";
echo "#main #mainsection .saved{color:#".$_SESSION['themecolour']."; border-bottom:1px solid #".$_SESSION['themecolour'].";}";
echo "#main #connections .title{color:#".$_SESSION['themecolour'].";}";
echo "#shelfmain #title{color:#".$_SESSION['themecolour'].";}";
echo "#stories .entry .storyname{color:#".$_SESSION['themecolour'].";}";
echo "#stories .entry .options a:hover{color:#".$_SESSION['themecolour'].";}";
echo "#mobilestories .entry .storyname{color:#".$_SESSION['themecolour'].";}";
echo "#mobilestories .entry .options a:hover{color:#".$_SESSION['themecolour'].";}";
echo "#topbar #topbuttons .toplink{background-color:#".$_SESSION['themecolour'].";}";
echo "#topbar #mainopt #names .fieldin:focus{border:1px solid #".$_SESSION['themecolour'].";}";
echo "#topbar #mainopt #subs #savedraft:hover{border:1px solid #".$_SESSION['themecolour'].";}";
echo "#topbar #mainopt #subs #savefull:hover{border:1px solid #".$_SESSION['themecolour'].";}";
echo "#main .title{color:#".$_SESSION['themecolour'].";}";
echo "#topbar #mainopts #openblurb{color:#".$_SESSION['themecolour']."; border-bottom:1px solid #".$_SESSION['themecolour'].";}";
echo "#topbar #mainopts #shelfappend{color:#".$_SESSION['themecolour']."; border-bottom:1px solid #".$_SESSION['themecolour'].";}";
echo "#topbar #mainopts #sharestory{color:#".$_SESSION['themecolour']."; border-bottom:1px solid #".$_SESSION['themecolour'].";}";
echo "#topbar #mainopts #favourite{color:#".$_SESSION['themecolour']."; border-bottom:1px solid #".$_SESSION['themecolour'].";}";
echo "#topbar #mainopts #editlink{color:#".$_SESSION['themecolour']."; border-bottom:1px solid #".$_SESSION['themecolour'].";}";
echo "#story #names #story{color:#".$_SESSION['themecolour'].";}";
echo "#story #names #writer{color:#".$_SESSION['themecolour'].";}";
echo "#story #names #favecount{color:#".$_SESSION['themecolour'].";}";
echo "#story #atts .infobit{color:#".$_SESSION['themecolour'].";}";
echo "#story #newshare .postshare{border:1px solid #".$_SESSION['themecolour'].";}";
echo "#story #buttons .acts{border:1px solid #".$_SESSION['themecolour']."; color:#".$_SESSION['themecolour'].";}";
echo "#story #buttons .acts:hover{background-color:#".$_SESSION['themecolour'].";}";
echo "#story #buttons .facts{border:1px solid #".$_SESSION['themecolour']."; background-color:#".$_SESSION['themecolour'].";}";
echo "#story #comments .post .del{color:#".$_SESSION['themecolour'].";}";
echo "#story #comments #postcomment #commentcontent{color:#".$_SESSION['themecolour'].";}";
echo "#story #comments #postcomment #commentcontent:focus{border:1px solid #".$_SESSION['themecolour'].";}";
echo "#story #comments #postcomment #postnew{color:#".$_SESSION['themecolour']."; border:1px solid #".$_SESSION['themecolour'].";}";
echo "#story #comments #postcomment #postnew:hover{background-color:#".$_SESSION['themecolour'].";}";
echo "@media only screen and (max-width: 800px){";
echo "#story #buttons .acts{border:none; border-bottom:1px solid #".$_SESSION['themecolour'].";}";
echo "#story #buttons .facts{border:none; border-bottom:1px solid #".$_SESSION['themecolour'].";}";
echo "#main #connections .entry .name img{background-color:#".$_SESSION['themecolour'].";}";
echo "#shelfmain .item .bottomdel{color:#".$_SESSION['themecolour'].";}";
echo "#shelfmain .item .bottomdel a{color:#".$_SESSION['themecolour'].";}";

echo "}";
echo "</style>";
}
?>